"""ELIZA (Weizenbaum, 1966) — the given engine, unchanged from Session A.

Extracted verbatim from ``../../notebooks/week-01-eliza.ipynb`` (§1). Three
ingredients and nothing else: a pattern table, a pronoun-reflection map, and a
fallback list. ELIZA has no model of the user, the topic, or the world — it is
six regular expressions and a dictionary. That is the whole point.

You do NOT edit this file. In ``starter.py`` you *extend* it (Task 1) and then
put the same inputs to it and to a real model (Task 2).
"""
import re
import random

random.seed(1)   # reproducible in class; remove for live improvisation

RULES = [
    (r"\bI am (.*)", ["How long have you been {0}?",
                      "Why do you say you are {0}?"]),
    (r"\bI feel (.*)", ["Do you often feel {0}?"]),
    (r"\bmy (mother|father|family)\b", ["Tell me more about your {0}."]),
    (r"\bbecause\b", ["Is that the real reason?"]),
    (r"\bno\b", ["Why not?"]),
    (r"\b(computer|machine)s?\b", ["Do machines worry you?"]),
]

FALLBACK = ["Please go on.", "What does that suggest to you?",
            "Can you elaborate on that?"]

REFLECT = {"i": "you", "me": "you", "my": "your", "am": "are",
           "you": "I", "your": "my", "are": "am"}


def reflect(text):
    return " ".join(REFLECT.get(w, w) for w in text.lower().split())


def respond(text):
    for pattern, templates in RULES:
        m = re.search(pattern, text, re.IGNORECASE)
        if m:
            groups = [reflect(g) for g in m.groups()]
            return random.choice(templates).format(*groups)
    return random.choice(FALLBACK)


if __name__ == "__main__":
    # §1 — how small it is.
    print("ELIZA is", sum(len(t) for _, t in RULES) + len(FALLBACK),
          "canned responses.\n")

    # §2 — it works for about six exchanges.
    conversation = [
        "I am not feeling great about the exam",
        "I feel anxious most of the time",
        "My mother thinks I should study more",
        "I did badly because I did not sleep",
    ]
    for line in conversation:
        print(f"you  > {line}")
        print(f"ELIZA> {respond(line)}\n")

    # §3 — now break it. Four different KINDS of failure.
    print("--- deliberate failures ---\n")
    probes = [
        ("I am not feeling great about the exam",
         "WORKS — pattern matched, pronouns reflected"),
        ("Do you think I should drop this course?",
         "NO MODEL OF THE QUESTION — a direct request for advice gets a deflection"),
        ("My mother is a doctor and my father is a lawyer",
         "IGNORED HALF THE SENTENCE — first match wins, the rest is invisible"),
        ("I am my own worst enemy",
         "ACCIDENTAL PROFUNDITY — syntactically perfect, semantically empty"),
    ]
    random.seed(1)
    for text, note in probes:
        print(f"you  > {text}")
        print(f"ELIZA> {respond(text)}")
        print(f"        ^ {note}\n")
